theme: jekyll-theme-cayman
title: kubernautas
description: Consultoria e treinamento em Kubernetes. Pensando em adotar Kubernetes ou precisando de ajuda com uma instalação atual? Fale conosco contato@kubernautas.com
google_analytics: UA-119543042-1
lang: pt-BR
